/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Menu;

/**
 *
 * @author nguyentranngocdiep
 */
public class Menu3 extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EasyButton = new javax.swing.JButton();
        NormalButton = new javax.swing.JButton();
        HardButton = new javax.swing.JButton();
        ExpertButton = new javax.swing.JButton();
        SnakeLabel = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        getContentPane().setLayout(null);

        EasyButton.setBackground(new java.awt.Color(255, 204, 0));
        EasyButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        EasyButton.setForeground(new java.awt.Color(204, 51, 0));
        EasyButton.setText("Easy");
        EasyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EasyButtonActionPerformed(evt);
            }
        });
        getContentPane().add(EasyButton);
        EasyButton.setBounds(290, 250, 200, 59);

        NormalButton.setBackground(new java.awt.Color(255, 204, 0));
        NormalButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        NormalButton.setForeground(new java.awt.Color(204, 51, 0));
        NormalButton.setText("Normal");
        NormalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NormalButtonActionPerformed(evt);
            }
        });
        getContentPane().add(NormalButton);
        NormalButton.setBounds(290, 320, 200, 59);

        HardButton.setBackground(new java.awt.Color(255, 204, 0));
        HardButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        HardButton.setForeground(new java.awt.Color(204, 51, 0));
        HardButton.setText("Hard");
        HardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HardButtonActionPerformed(evt);
            }
        });
        getContentPane().add(HardButton);
        HardButton.setBounds(290, 390, 200, 59);

        ExpertButton.setBackground(new java.awt.Color(255, 204, 0));
        ExpertButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        ExpertButton.setForeground(new java.awt.Color(204, 51, 0));
        ExpertButton.setText("Expert");
        ExpertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExpertButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ExpertButton);
        ExpertButton.setBounds(290, 460, 200, 59);

        SnakeLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\binguyen.com\\Documents\\NetBeansProjects\\snake\\res\\Menu\\snake.png")); // NOI18N
        SnakeLabel.setText("jLabel2");
        getContentPane().add(SnakeLabel);
        SnakeLabel.setBounds(260, 80, 250, 143);

        Background.setIcon(new javax.swing.ImageIcon("C:\\Users\\binguyen.com\\Documents\\NetBeansProjects\\snake\\res\\Menu\\bg.png")); // NOI18N
        Background.setText("jLabel1");
        getContentPane().add(Background);
        Background.setBounds(0, 10, 800, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NormalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NormalButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NormalButtonActionPerformed

    private void ExpertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExpertButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExpertButtonActionPerformed

    private void EasyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EasyButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EasyButtonActionPerformed

    private void HardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HardButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HardButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JButton EasyButton;
    private javax.swing.JButton ExpertButton;
    public javax.swing.JButton HardButton;
    private javax.swing.JButton NormalButton;
    private javax.swing.JLabel SnakeLabel;
    // End of variables declaration//GEN-END:variables
}
