/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Menu;
import GamePlay.ClassicGame;
import Leaderboard.LeaderboardChoice;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import java.util.Scanner;
import java.io.*;
import java.util.List;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.WindowConstants;
/**
 *
 * @author nguyentranngocdiep
 */
public class Menu extends JFrame {
public static enum STATE {
    START,
    GAME
}
public static STATE State = STATE.GAME;
    /**
     * Creates new form Menu
     */
    public  Menu() {
        SnakeLabels = new JLabel();
        Background = new JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 600));
        setLocationRelativeTo(null);
        setResizable(false);
        setLayout(null);
        
        SnakeLabels.setIcon(new javax.swing.ImageIcon("res\\Menu\\snake.png")); // NOI18N
        SnakeLabels.setText("Title");
        add(SnakeLabels);
        SnakeLabels.setBounds(370, 80, 250, 143);
     
        Background.setIcon(new javax.swing.ImageIcon("res\\Menu\\bg1.png")); // NOI18N
        Background.setText("Background");
        add(Background);
        Background.setBounds(0, 0, 1000, 600);
        pack();
        
       if (State == STATE.GAME){
            StartMenu();
            
        }
       else if(State == STATE.GAME){
           GameMenu();
       }
       
    }
    public void StartMenu(){
        Start();
    }
    public void GameMenu(){
        Classic();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//
    public void Start(){
        StartButton = new JButton();
        StartButton.setBackground(new Color(255, 204, 0));
        StartButton.setFont(new Font("Berlin Sans FB Demi", 1, 24));
        StartButton.setForeground(new Color(204, 51, 0));
        StartButton.setText("Start");
        StartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartButtonActionPerformed(evt);
            }
        });
        add(StartButton);
        StartButton.setBounds(400, 230, 200, 59);
    }
    private void Classic(){
        ClassicButton = new JButton();
        ClassicButton.setBackground(new java.awt.Color(255, 204, 0));
        ClassicButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        ClassicButton.setForeground(new java.awt.Color(204, 51, 0));
        ClassicButton.setText("Classic Mode");
        ClassicButton.setVisible(true);
        ClassicButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                ClassicButtonActionPerformed(evt);
            }
        });
        add(ClassicButton);
        ClassicButton.setBounds(400, 250, 200, 59);
        
    }
    private void Menu1() {     
        StoreButton = new JButton();
        LeaderBoardButton = new JButton();
        ExitButton = new JButton();
        
        StoreButton.setBackground(new Color(255, 204, 0));
        StoreButton.setFont(new Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        StoreButton.setForeground(new Color(204, 51, 0));
        StoreButton.setText("Store");
        StoreButton.addActionListener(new ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StoreButtonActionPerformed(evt);
            }
        });
        add(StoreButton);
        StoreButton.setBounds(400, 300, 200, 59);

        LeaderBoardButton.setBackground(new java.awt.Color(255, 204, 0));
        LeaderBoardButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        LeaderBoardButton.setForeground(new java.awt.Color(204, 51, 0));
        LeaderBoardButton.setText("Leaderboard");
        LeaderBoardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LeaderBoardButtonActionPerformed(evt);
            }
        });
        add(LeaderBoardButton);
        LeaderBoardButton.setBounds(400, 370, 200, 59);

        ExitButton.setBackground(new java.awt.Color(255, 204, 0));
        ExitButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        ExitButton.setForeground(new java.awt.Color(204, 51, 0));
        ExitButton.setText("Exit");
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });
        add(ExitButton);
        ExitButton.setBounds(400, 440, 200, 59);

       
    }// </editor-fold>
    private void Menu2(){
        
        TimeButton = new JButton();
        BackButton = new JButton();
        SnakeLabels = new JLabel();
        Background = new JLabel();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new Dimension(1000, 600));
//        setLocationRelativeTo(null);
        setResizable(false);
        setLayout(null);

        

        TimeButton.setBackground(new java.awt.Color(255, 204, 0));
        TimeButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        TimeButton.setForeground(new java.awt.Color(204, 51, 0));
        TimeButton.setText("Time Mode");
        TimeButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                TimeButtonActionPerformed(evt);
            }
        });
        add(TimeButton);
        TimeButton.setBounds(400, 320, 200, 59);
        
        BackButton.setBackground(new Color(255, 204, 0));
        BackButton.setFont(new Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        BackButton.setForeground(new Color(204, 51, 0));
        BackButton.setText("Back to Main Menu");
        BackButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        add(BackButton);
        BackButton.setBounds(400, 390, 200, 59);

        SnakeLabels.setIcon(new ImageIcon("res\\Menu\\snake.png")); // NOI18N
        SnakeLabels.setText("Title");
        add(SnakeLabels);
        SnakeLabels.setBounds(370, 80, 250, 143);

        Background.setIcon(new ImageIcon("res\\Menu\\bg1.png")); // NOI18N
        Background.setText("Background");
        add(Background);
        Background.setBounds(0, 0, 1000, 600);

        pack();
    }
    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//
        // TODO add your handling code here:
        System.exit(0);
         

    }//

    private void StartButtonActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
                      Menu.State = Menu.STATE.GAME;
    }//
    private void StoreButtonActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void LeaderBoardButtonActionPerformed(java.awt.event.ActionEvent evt) {//
        // TODO add your handling code here:
        LeaderboardChoice l = new LeaderboardChoice();
        l.setVisible(true);
        setVisible(false);
    }//
      public void ClassicButtonActionPerformed(ActionEvent evt) {                                              
        // TODO add your handling code here:
        ClassicGame s = new ClassicGame();
        s.setVisible(true);
        setVisible(false);
    } 

    private void TimeButtonActionPerformed(ActionEvent evt) {
        // TODO add your handling code here:
        Menu3 menu3 = new Menu3();
        menu3.setVisible(true);
        setVisible(false);
    } 
    
    private void BackButtonActionPerformed(ActionEvent evt) {
        // TODO add your handling code here:
        Menu m = new Menu();
        m.setVisible(true);
        setVisible(false);
    } 

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//
    public JLabel Background;
    public JButton ExitButton;
    public JButton LeaderBoardButton;
    public JLabel SnakeLabels;
    public JButton StartButton;
    public JButton StoreButton;
    public JButton ClassicButton, TimeButton, BackButton;
    // End of variables declaration//
}
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

