/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Menu;

import GamePlay.Snake;

/**
 *
 * @author nguyentranngocdiep
 */
public class Menu2 extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code"> 
    private void initComponents() {

        ClassicButton = new javax.swing.JButton();
        TimeButton = new javax.swing.JButton();
        SnakeLabels = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 600));
        setLocationRelativeTo(null);
        setResizable(false);
        setLayout(null);

        ClassicButton.setBackground(new java.awt.Color(255, 204, 0));
        ClassicButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        ClassicButton.setForeground(new java.awt.Color(204, 51, 0));
        ClassicButton.setText("Classic Mode");
        ClassicButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClassicButtonActionPerformed(evt);
            }
        });
        add(ClassicButton);
        ClassicButton.setBounds(400, 250, 200, 59);

        TimeButton.setBackground(new java.awt.Color(255, 204, 0));
        TimeButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        TimeButton.setForeground(new java.awt.Color(204, 51, 0));
        TimeButton.setText("Time Mode");
        TimeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TimeButtonActionPerformed(evt);
            }
        });
        add(TimeButton);
        TimeButton.setBounds(400, 350, 200, 59);

        SnakeLabels.setIcon(new javax.swing.ImageIcon("res\\Menu\\snake.png")); // NOI18N
        SnakeLabels.setText("Title");
        add(SnakeLabels);
        SnakeLabels.setBounds(370, 80, 250, 143);

        Background.setIcon(new javax.swing.ImageIcon("res\\Menu\\bg1.png")); // NOI18N
        Background.setText("Background");
        add(Background);
        Background.setBounds(0, 0, 1000, 600);

        pack();
    }// </editor-fold>                        

    private void ClassicButtonActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
        Snake s = new Snake();
        s.setVisible(true);
        setVisible(false);
    } 

    private void TimeButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        Menu3 menu3 = new Menu3();
        menu3.setVisible(true);
        setVisible(false);
    } 

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JLabel Background;
    private javax.swing.JButton ClassicButton;
    private javax.swing.JLabel SnakeLabels;
    private javax.swing.JButton TimeButton;
    // End of variables declaration
}
