/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Leaderboard;

import java.awt.Font;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Bloo
 */
public class LeaderboardTimeChoice extends JFrame {
    
    public LeaderboardTimeChoice() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code"> 
    private void initComponents() {

        EasyButton = new JButton();
        NormalButton = new JButton();
        HardButton = new JButton();
        ExpertButton = new JButton();
        BackButton = new JButton();
        LeaderLabel = new JLabel();
        Background = new JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 600));
        setLocationRelativeTo(null);
        setResizable(false);
        setLayout(null);

        EasyButton.setBackground(new java.awt.Color(255, 204, 0));
        EasyButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        EasyButton.setForeground(new java.awt.Color(204, 51, 0));
        EasyButton.setText("Easy");
        EasyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EasyButtonActionPerformed(evt);
            }
        });
        add(EasyButton);
        EasyButton.setBounds(400, 150, 200, 59);

        NormalButton.setBackground(new java.awt.Color(255, 204, 0));
        NormalButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        NormalButton.setForeground(new java.awt.Color(204, 51, 0));
        NormalButton.setText("Normal");
        NormalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NormalButtonActionPerformed(evt);
            }
        });
        add(NormalButton);
        NormalButton.setBounds(400, 230, 200, 59);

        HardButton.setBackground(new java.awt.Color(255, 204, 0));
        HardButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        HardButton.setForeground(new java.awt.Color(204, 51, 0));
        HardButton.setText("Hard");
        HardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HardButtonActionPerformed(evt);
            }
        });
        add(HardButton);
        HardButton.setBounds(400, 310, 200, 59);

        ExpertButton.setBackground(new java.awt.Color(255, 204, 0));
        ExpertButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        ExpertButton.setForeground(new java.awt.Color(204, 51, 0));
        ExpertButton.setText("Expert");
        ExpertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExpertButtonActionPerformed(evt);
            }
        });
        add(ExpertButton);
        ExpertButton.setBounds(400, 390, 200, 59);

        BackButton.setBackground(new java.awt.Color(255, 204, 0));
        BackButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        BackButton.setForeground(new java.awt.Color(204, 51, 0));
        BackButton.setText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        add(BackButton);
        BackButton.setBounds(400, 490, 200, 59);
        
        LeaderLabel.setText("Leaderboard");
        LeaderLabel.setFont(new Font("Berlin Sans FB Demi", 1, 36));
        add(LeaderLabel);
        LeaderLabel.setBounds(395, 20, 250, 143);

        Background.setIcon(new ImageIcon("res\\Menu\\bg1.png")); // NOI18N
        Background.setText("Background");
        add(Background);
        Background.setBounds(0, 0, 1000, 600);

        pack();
    }// </editor-fold> 

    private void NormalButtonActionPerformed(java.awt.event.ActionEvent evt) { 
        // TODO add your handling code here:
    } 

    private void ExpertButtonActionPerformed(java.awt.event.ActionEvent evt) { 
        // TODO add your handling code here:
    } 

    private void EasyButtonActionPerformed(java.awt.event.ActionEvent evt) { 
        // TODO add your handling code here:
        Leaderboard e = new Leaderboard();
        e.setVisible(true);
        setVisible(false);
    } 

    private void HardButtonActionPerformed(java.awt.event.ActionEvent evt) { 
        // TODO add your handling code here:
    } 
    
    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) { 
        // TODO add your handling code here:
        LeaderboardChoice l = new LeaderboardChoice();
        l.setVisible(true);
        setVisible(false);
    } 

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LeaderboardTimeChoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LeaderboardTimeChoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LeaderboardTimeChoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LeaderboardTimeChoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LeaderboardTimeChoice().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify 
    private JLabel Background, LeaderLabel;
    public JButton EasyButton, NormalButton, HardButton, ExpertButton, BackButton;
    // End of variables declaration 
    
}
